/**
 * generate-roots.mjs
 * Reads parsed-data.json and generates content/roots.ts
 * with AI-enriched data for all roots.
 *
 * Usage: node scripts/generate-roots.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = resolve(__dirname, '..');
const PARSED = JSON.parse(readFileSync(resolve(__dirname, 'output/parsed-data.json'), 'utf-8'));
const OUTPUT = resolve(ROOT_DIR, 'content/roots.ts');

// ── AI-enriched root data ────────────────────────────────────
// Each entry: [slug, { enMeaning, etymology, origin, semanticDomains, overview_en, overview_zh, originSummary_en, originSummary_zh, relatedRoots, grimmLawGroup? }]

const ENRICHMENT = {
  act: {
    enMeaning: 'do, act, drive',
    etymology: 'Latin agere, actum',
    origin: 'Latin',
    domains: ['action'],
    overview_en:
      'A foundational Latin root appearing in words about doing, performing, and driving action.',
    overview_zh: '基础拉丁词根，出现在关于做、执行和驱动行动的词汇中。',
    originSummary_en: 'From Latin "agere" (to do, drive) and its past participle "actum".',
    originSummary_zh: '源自拉丁语 agere（做、驱动）及其过去分词 actum。',
    related: ['fac', 'mov', 'pel'],
    grimm: 'g/k/c/q/qu/h/j',
  },
  ali: {
    enMeaning: 'other, another',
    etymology: 'Latin alius',
    origin: 'Latin',
    domains: ['change'],
    overview_en: 'A Latin root meaning "other", found in words about alternatives and otherness.',
    overview_zh: '拉丁词根，意为"其他的"，出现在关于替代和差异的词汇中。',
    originSummary_en: 'From Latin "alius" meaning other, another.',
    originSummary_zh: '源自拉丁语 alius，意为其他的、另一个。',
    related: ['vers', 'nov'],
  },
  am: {
    enMeaning: 'love',
    etymology: 'Latin amāre',
    origin: 'Latin',
    domains: ['emotion'],
    overview_en:
      'A Latin root for love and affection, appearing in romantic and social vocabulary.',
    overview_zh: '表示爱和感情的拉丁词根，出现在浪漫和社交词汇中。',
    originSummary_en: 'From Latin "amāre" (to love) and "amor" (love).',
    originSummary_zh: '源自拉丁语 amāre（爱）和 amor（爱情）。',
    related: ['path', 'viv'],
  },
  anim: {
    enMeaning: 'breath, spirit, life',
    etymology: 'Latin anima',
    origin: 'Latin',
    domains: ['breathing', 'life'],
    overview_en: 'Connects to breath and spirit, forming words about life force and living beings.',
    overview_zh: '与呼吸和灵魂相关，构成关于生命力和生物的词汇。',
    originSummary_en: 'From Latin "anima" (breath, soul, spirit).',
    originSummary_zh: '源自拉丁语 anima（呼吸、灵魂、精神）。',
    related: ['spir', 'viv', 'bio'],
  },
  apt: {
    enMeaning: 'fit, suitable',
    etymology: 'Latin aptus',
    origin: 'Latin',
    domains: ['other'],
    overview_en:
      'A root about fitness and suitability, appearing in words about adaptation and skill.',
    overview_zh: '关于适合和适当的词根，出现在适应和技能的词汇中。',
    originSummary_en: 'From Latin "aptus" (fit, suitable, proper).',
    originSummary_zh: '源自拉丁语 aptus（适合的、适当的）。',
    related: ['ept', 'dec'],
  },
  aster: {
    enMeaning: 'star',
    etymology: 'Greek astḗr (ἀστήρ)',
    origin: 'Greek',
    domains: ['nature', 'light'],
    overview_en: 'A Greek root for stars, used in astronomy and celestial vocabulary.',
    overview_zh: '希腊词根，表示星星，用于天文学和天体相关词汇。',
    originSummary_en: 'From Greek "astḗr" (star) and "astron" (constellation).',
    originSummary_zh: '源自希腊语 astḗr（星星）和 astron（星座）。',
    related: ['nav', 'sol'],
  },
  bar: {
    enMeaning: 'bar, rod, obstacle',
    etymology: 'Latin barra / Old French barre',
    origin: 'Latin',
    domains: ['other'],
    overview_en:
      'A root meaning rod or obstacle, producing words about barriers, prohibition, and enclosure.',
    overview_zh: '表示棍棒或障碍的词根，产生关于屏障、禁止和围栏的词汇。',
    originSummary_en: 'From Late Latin "barra" (bar, rod) via Old French "barre".',
    originSummary_zh: '源自晚期拉丁语 barra（棍棒）经由古法语 barre。',
    related: ['strain', 'forc'],
    grimm: 'b/p/f/v',
  },
  bio: {
    enMeaning: 'life',
    etymology: 'Greek βίος (bíos)',
    origin: 'Greek',
    domains: ['life', 'knowledge'],
    overview_en:
      'An essential root for life sciences, appearing in academic and popular vocabulary.',
    overview_zh: '生命科学领域的基础词根，在学术和日常词汇中都十分常见。',
    originSummary_en:
      'Derived from the Greek "βίος" meaning life, used across biology-related terminology.',
    originSummary_zh: '源自希腊语 "βίος"，意为"生命"，广泛用于生物学相关术语。',
    related: ['chron', 'geo', 'viv'],
  },
  bot: {
    enMeaning: 'plant, herb',
    etymology: 'Greek botanē (βοτάνη)',
    origin: 'Greek',
    domains: ['plants'],
    overview_en: 'A Greek root for plants and herbs, the basis of botanical vocabulary.',
    overview_zh: '希腊词根，表示植物和草本，是植物学词汇的基础。',
    originSummary_en: 'From Greek "botanē" (plant, herb, pasture).',
    originSummary_zh: '源自希腊语 botanē（植物、草本、牧场）。',
    related: ['bio', 'nat'],
  },
  cand: {
    enMeaning: 'white, glow, heat',
    etymology: 'Latin candēre',
    origin: 'Latin',
    domains: ['light'],
    overview_en:
      'A Latin root about whiteness and glowing, found in words about candles, candidness, and heat.',
    overview_zh: '拉丁词根，关于白色和发光，出现在蜡烛、坦率和热度的词汇中。',
    originSummary_en: 'From Latin "candēre" (to shine, glow white).',
    originSummary_zh: '源自拉丁语 candēre（发光、发白光）。',
    related: ['light', 'sol'],
  },
  cap: {
    enMeaning: 'take, seize, hold',
    etymology: 'Latin capere',
    origin: 'Latin',
    domains: ['holding'],
    overview_en:
      'One of the most productive Latin roots, generating hundreds of words about taking, receiving, and holding.',
    overview_zh: '最高产的拉丁词根之一，产生了大量关于拿取、接收和持有的词汇。',
    originSummary_en: 'From Latin "capere" (to take, seize) with variants cip-, cept-, ceiv-.',
    originSummary_zh: '源自拉丁语 capere（拿取、抓住），变体有 cip-、cept-、ceiv-。',
    related: ['tain', 'fer', 'tra'],
  },
  car: {
    enMeaning: 'vehicle, run, carry',
    etymology: 'Latin carrus / currere',
    origin: 'Latin',
    domains: ['transport', 'movement'],
    overview_en:
      'A root family around vehicles and running, from chariots to modern cars and careers.',
    overview_zh: '关于车辆和奔跑的词根家族，从战车到现代汽车和事业。',
    originSummary_en: 'From Latin "carrus" (wheeled vehicle) and "currere" (to run).',
    originSummary_zh: '源自拉丁语 carrus（轮式车辆）和 currere（跑）。',
    related: ['port', 'mov', 'fer'],
  },
  carn: {
    enMeaning: 'flesh, meat',
    etymology: 'Latin carō, carnis',
    origin: 'Latin',
    domains: ['body', 'food'],
    overview_en:
      'A Latin root for flesh, appearing in words about meat, physical embodiment, and festivals.',
    overview_zh: '拉丁词根，表示肉，出现在关于肉类、身体化和节日的词汇中。',
    originSummary_en: 'From Latin "carō" (genitive "carnis"), meaning flesh, meat.',
    originSummary_zh: '源自拉丁语 carō（属格 carnis），意为肉、肉体。',
    related: ['viv', 'cid'],
  },
  ced: {
    enMeaning: 'go, yield, move',
    etymology: 'Latin cēdere',
    origin: 'Latin',
    domains: ['movement', 'walking'],
    overview_en:
      'A Latin root about going and yielding, one of the most versatile roots in English.',
    overview_zh: '关于行走和让步的拉丁词根，是英语中最多用的词根之一。',
    originSummary_en: 'From Latin "cēdere" (to go, yield, withdraw) with past participle "cessum".',
    originSummary_zh: '源自拉丁语 cēdere（走、让步、撤退），过去分词 cessum。',
    related: ['ven', 'vad', 'it'],
  },
  cern: {
    enMeaning: 'separate, distinguish, sift',
    etymology: 'Latin cernere',
    origin: 'Latin',
    domains: ['choosing', 'knowledge'],
    overview_en:
      'A root about separating and distinguishing, forming words about judgment and perception.',
    overview_zh: '关于分离和辨别的词根，构成关于判断和感知的词汇。',
    originSummary_en: 'From Latin "cernere" (to sift, separate, distinguish).',
    originSummary_zh: '源自拉丁语 cernere（筛选、分离、辨别）。',
    related: ['lect', 'jur', 'cid'],
  },
  cid: {
    enMeaning: 'cut, kill',
    etymology: 'Latin caedere',
    origin: 'Latin',
    domains: ['cutting'],
    overview_en:
      'A Latin root about cutting and killing, found in words about decisions, incidents, and endings.',
    overview_zh: '拉丁词根，关于切割和杀戮，出现在关于决定、事件和终结的词汇中。',
    originSummary_en: 'From Latin "caedere" (to cut, strike, kill).',
    originSummary_zh: '源自拉丁语 caedere（切割、打击、杀死）。',
    related: ['tail', 'mort', 'cern'],
  },
  circ: {
    enMeaning: 'circle, ring',
    etymology: 'Latin circus / Greek kirkos',
    origin: 'Latin',
    domains: ['movement', 'turning'],
    overview_en:
      'A root about circles and rings, producing words about circulation and surrounding.',
    overview_zh: '关于圆和环的词根，产生关于循环和环绕的词汇。',
    originSummary_en: 'From Latin "circus" (circle, ring) and Greek "kirkos" (ring).',
    originSummary_zh: '源自拉丁语 circus（圆、环）和希腊语 kirkos（环）。',
    related: ['rot', 'vers', 'trop'],
  },
  claim: {
    enMeaning: 'shout, call out',
    etymology: 'Latin clāmāre',
    origin: 'Latin',
    domains: ['speech'],
    overview_en:
      'A root about shouting and calling, found in words about declarations and demands.',
    overview_zh: '关于呼喊和叫喊的词根，出现在关于宣言和要求的词汇中。',
    originSummary_en: 'From Latin "clāmāre" (to shout, cry out, call).',
    originSummary_zh: '源自拉丁语 clāmāre（呼喊、叫喊、呼唤）。',
    related: ['voc', 'dic', 'fess'],
  },
  chron: {
    enMeaning: 'time',
    etymology: 'Greek χρόνος (khrónos)',
    origin: 'Greek',
    domains: ['time'],
    overview_en: 'Chron connects terms about time, sequence, and historical narration.',
    overview_zh: 'Chron 关联时间、顺序和历史叙述相关的词汇。',
    originSummary_en: 'From "χρόνος" meaning time, it forms words about timekeeping and history.',
    originSummary_zh: '源自希腊语 "χρόνος"，表示时间，多见于计时和历史相关词汇。',
    related: ['bio', 'geo'],
  },
  crim: {
    enMeaning: 'accusation, crime',
    etymology: 'Latin crīmen',
    origin: 'Latin',
    domains: ['law'],
    overview_en:
      'A root about accusation and wrongdoing, forming the vocabulary of crime and justice.',
    overview_zh: '关于控诉和犯罪的词根，构成犯罪和司法的词汇。',
    originSummary_en: 'From Latin "crīmen" (accusation, charge, crime).',
    originSummary_zh: '源自拉丁语 crīmen（控诉、指控、罪行）。',
    related: ['jur', 'pun', 'lect'],
  },
  cult: {
    enMeaning: 'cultivate, till, worship',
    etymology: 'Latin colere, cultum',
    origin: 'Latin',
    domains: ['society', 'nature'],
    overview_en:
      'A root connecting agriculture and culture, from tilling fields to cultivating knowledge.',
    overview_zh: '连接农业和文化的词根，从耕作田地到培养知识。',
    originSummary_en:
      'From Latin "colere" (to cultivate, tend, worship) with past participle "cultum".',
    originSummary_zh: '源自拉丁语 colere（耕作、照料、崇拜），过去分词 cultum。',
    related: ['nat', 'gen', 'hum'],
  },
  dec: {
    enMeaning: 'fitting, proper, graceful',
    etymology: 'Latin decēre',
    origin: 'Latin',
    domains: ['other'],
    overview_en: 'A root about propriety and grace, forming words about decency and decoration.',
    overview_zh: '关于得体和优雅的词根，构成关于体面和装饰的词汇。',
    originSummary_en: 'From Latin "decēre" (to be fitting, to be proper).',
    originSummary_zh: '源自拉丁语 decēre（适合、得体）。',
    related: ['apt', 'norm'],
  },
  dic: {
    enMeaning: 'say, speak, declare',
    etymology: 'Latin dīcere',
    origin: 'Latin',
    domains: ['speech'],
    overview_en:
      'A central Latin root for speech, producing words about saying, declaring, and indicating.',
    overview_zh: '核心拉丁语言词根，产生关于说、宣告和指示的词汇。',
    originSummary_en: 'From Latin "dīcere" (to say, speak) with past participle "dictum".',
    originSummary_zh: '源自拉丁语 dīcere（说、讲），过去分词 dictum。',
    related: ['fess', 'claim', 'voc'],
    grimm: 'd/t/s/z',
  },
  dit: {
    enMeaning: 'give',
    etymology: 'Latin dare, datum',
    origin: 'Latin',
    domains: ['giving'],
    overview_en:
      'A root about giving, appearing in words about donation, tradition, and endowment.',
    overview_zh: '关于给予的词根，出现在关于捐赠、传统和天赋的词汇中。',
    originSummary_en: 'From Latin "dare" (to give) with forms "datum", "dōnum", and "dōtum".',
    originSummary_zh: '源自拉丁语 dare（给予），形式有 datum、dōnum 和 dōtum。',
    related: ['miss', 'fer', 'port'],
    grimm: 'd/t/s/z',
  },
  dom: {
    enMeaning: 'house, master, rule',
    etymology: 'Latin domus / dominus',
    origin: 'Latin',
    domains: ['society', 'power'],
    overview_en: 'A root about houses and mastery, from domestic spaces to dominion and control.',
    overview_zh: '关于房屋和统治的词根，从家庭空间到统治和控制。',
    originSummary_en: 'From Latin "domus" (house) and "dominus" (master, lord).',
    originSummary_zh: '源自拉丁语 domus（房屋）和 dominus（主人、统治者）。',
    related: ['urb', 'loc'],
    grimm: 'd/t/s/z',
  },
  dorm: {
    enMeaning: 'sleep',
    etymology: 'Latin dormīre',
    origin: 'Latin',
    domains: ['sleep'],
    overview_en: 'A Latin root for sleep, forming words about dormancy and sleeping places.',
    overview_zh: '拉丁词根，表示睡眠，构成关于休眠和睡眠场所的词汇。',
    originSummary_en: 'From Latin "dormīre" (to sleep).',
    originSummary_zh: '源自拉丁语 dormīre（睡觉）。',
    related: ['mort', 'viv'],
    grimm: 'd/t/s/z',
  },
  ept: {
    enMeaning: 'fit, capable',
    etymology: 'Latin aptus (variant)',
    origin: 'Latin',
    domains: ['other'],
    overview_en: 'A variant of apt- appearing in words about skill and capability.',
    overview_zh: 'apt- 的变体，出现在关于技能和能力的词汇中。',
    originSummary_en: 'Variant of Latin "aptus" (fit), appearing in compound forms.',
    originSummary_zh: '拉丁语 aptus（适合）的变体，出现在复合词中。',
    related: ['apt', 'dec'],
  },
  fac: {
    enMeaning: 'do, make',
    etymology: 'Latin facere',
    origin: 'Latin',
    domains: ['making', 'action'],
    overview_en:
      'One of the most prolific Latin roots, generating vast vocabulary about making and doing.',
    overview_zh: '最高产的拉丁词根之一，产生了大量关于制造和做事的词汇。',
    originSummary_en: 'From Latin "facere" (to do, make) with variants fec-, fic-, fit-, fact-.',
    originSummary_zh: '源自拉丁语 facere（做、制造），变体有 fec-、fic-、fit-、fact-。',
    related: ['act', 'gen', 'fer'],
    grimm: 'b/p/f/v',
  },
  fer: {
    enMeaning: 'carry, bear, bring',
    etymology: 'Latin ferre',
    origin: 'Latin',
    domains: ['transport'],
    overview_en:
      'A major Latin root for carrying and bearing, present in everyday and academic English.',
    overview_zh: '主要拉丁搬运词根，在日常和学术英语中都很常见。',
    originSummary_en: 'From Latin "ferre" (to carry, bear, bring).',
    originSummary_zh: '源自拉丁语 ferre（搬运、承载、带来）。',
    related: ['port', 'gest', 'car'],
    grimm: 'b/p/f/v',
  },
  fess: {
    enMeaning: 'speak, declare',
    etymology: 'Latin fatērī, fassus',
    origin: 'Latin',
    domains: ['speech'],
    overview_en: 'A root about open declaration, forming words about confession and profession.',
    overview_zh: '关于公开声明的词根，构成关于忏悔和职业的词汇。',
    originSummary_en: 'From Latin "fatērī" (to acknowledge, confess), past participle "fassus".',
    originSummary_zh: '源自拉丁语 fatērī（承认、忏悔），过去分词 fassus。',
    related: ['dic', 'claim', 'voc'],
    grimm: 'b/p/f/v',
  },
  flu: {
    enMeaning: 'flow',
    etymology: 'Latin fluere',
    origin: 'Latin',
    domains: ['flowing'],
    overview_en:
      'A Latin root about flowing, producing words about fluidity, influence, and abundance.',
    overview_zh: '关于流动的拉丁词根，产生关于流畅、影响和丰富的词汇。',
    originSummary_en: 'From Latin "fluere" (to flow) with variants flux-, fus-.',
    originSummary_zh: '源自拉丁语 fluere（流动），变体有 flux-、fus-。',
    related: ['lav', 'vers', 'mov'],
    grimm: 'b/p/f/v',
  },
  forc: {
    enMeaning: 'strong, strength',
    etymology: 'Latin fortis',
    origin: 'Latin',
    domains: ['strength', 'power'],
    overview_en:
      'A root about strength and force, forming words about power, effort, and reinforcement.',
    overview_zh: '关于力量和强壮的词根，构成关于权力、努力和加强的词汇。',
    originSummary_en: 'From Latin "fortis" (strong, powerful).',
    originSummary_zh: '源自拉丁语 fortis（强壮的、有力的）。',
    related: ['val', 'pel', 'press'],
    grimm: 'b/p/f/v',
  },
  fortun: {
    enMeaning: 'chance, luck, fortune',
    etymology: 'Latin fortūna',
    origin: 'Latin',
    domains: ['other'],
    overview_en: 'A root about luck and chance, from the Roman goddess Fortuna.',
    overview_zh: '关于运气和机遇的词根，源自罗马女神福尔图娜。',
    originSummary_en: 'From Latin "fortūna" (fortune, luck, fate).',
    originSummary_zh: '源自拉丁语 fortūna（命运、运气、财富）。',
    related: ['forc', 'dit'],
  },
  fund: {
    enMeaning: 'bottom, base, foundation',
    etymology: 'Latin fundus',
    origin: 'Latin',
    domains: ['building'],
    overview_en:
      'A root about foundations, forming words about establishing, funding, and fundamentals.',
    overview_zh: '关于基础的词根，构成关于建立、资助和基本原理的词汇。',
    originSummary_en: 'From Latin "fundus" (bottom, base) and "fundāre" (to lay the foundation).',
    originSummary_zh: '源自拉丁语 fundus（底部、基础）和 fundāre（奠基）。',
    related: ['st', 'loc'],
    grimm: 'b/p/f/v',
  },
  gen: {
    enMeaning: 'birth, produce, race',
    etymology: 'Latin genus / Greek genos',
    origin: 'Latin',
    domains: ['birth', 'making'],
    overview_en:
      'A prolific root about birth and production, spanning biology, society, and technology.',
    overview_zh: '高产词根，关于出生和产生，横跨生物学、社会和技术领域。',
    originSummary_en: 'From Latin "genus" (birth, race, kind) and Greek "genos" (race, kind).',
    originSummary_zh: '源自拉丁语 genus（出生、种族、种类）和希腊语 genos。',
    related: ['nat', 'bio', 'ori'],
    grimm: 'g/k/c/q/qu/h/j',
  },
  geo: {
    enMeaning: 'earth, land',
    etymology: 'Greek γῆ (gē)',
    origin: 'Greek',
    domains: ['earth', 'nature'],
    overview_en: 'Geo links earth science and spatial reasoning vocabulary.',
    overview_zh: 'Geo 将地球科学与空间概念的词汇连接起来。',
    originSummary_en: 'From "γῆ" meaning earth, appearing in geography and geology-related terms.',
    originSummary_zh: '源自希腊语 "γῆ"，意为"土地/大地"，常见于地理和地质词汇。',
    related: ['bio', 'chron', 'hum'],
  },
  gest: {
    enMeaning: 'carry, bear',
    etymology: 'Latin gerere, gestum',
    origin: 'Latin',
    domains: ['transport'],
    overview_en:
      'A root about carrying and bearing, forming words about digestion, suggestion, and gestures.',
    overview_zh: '关于承载和搬运的词根，构成关于消化、建议和手势的词汇。',
    originSummary_en: 'From Latin "gerere" (to carry, wage, perform), past participle "gestum".',
    originSummary_zh: '源自拉丁语 gerere（搬运、发动、执行），过去分词 gestum。',
    related: ['fer', 'port', 'car'],
  },
  glob: {
    enMeaning: 'sphere, ball',
    etymology: 'Latin globus',
    origin: 'Latin',
    domains: ['earth'],
    overview_en: 'A root about spheres and globes, forming words about global scope and shape.',
    overview_zh: '关于球体和地球的词根，构成关于全球范围和形状的词汇。',
    originSummary_en: 'From Latin "globus" (sphere, ball, globe).',
    originSummary_zh: '源自拉丁语 globus（球体、球、地球仪）。',
    related: ['circ', 'geo'],
  },
  grav: {
    enMeaning: 'heavy, weighty',
    etymology: 'Latin gravis',
    origin: 'Latin',
    domains: ['other'],
    overview_en: 'A root about heaviness and seriousness, from gravity to gravitas.',
    overview_zh: '关于沉重和严肃的词根，从重力到庄重。',
    originSummary_en: 'From Latin "gravis" (heavy, weighty, serious).',
    originSummary_zh: '源自拉丁语 gravis（沉重的、严肃的）。',
    related: ['press', 'forc'],
  },
  her: {
    enMeaning: 'stick, cling',
    etymology: 'Latin haerēre',
    origin: 'Latin',
    domains: ['binding'],
    overview_en:
      'A root about sticking and clinging, forming words about adhesion, coherence, and inheritance.',
    overview_zh: '关于粘附和依附的词根，构成关于粘合、连贯和继承的词汇。',
    originSummary_en: 'From Latin "haerēre" (to stick, cling, adhere).',
    originSummary_zh: '源自拉丁语 haerēre（粘住、依附、坚持）。',
    related: ['tain', 'strain'],
  },
  hospit: {
    enMeaning: 'guest, host',
    etymology: 'Latin hospes, hospitis',
    origin: 'Latin',
    domains: ['society'],
    overview_en: 'A root about guests and hosting, from hospitals to hospitality.',
    overview_zh: '关于客人和招待的词根，从医院到好客之道。',
    originSummary_en: 'From Latin "hospes" (guest, host, stranger).',
    originSummary_zh: '源自拉丁语 hospes（客人、主人、陌生人）。',
    related: ['dom', 'urb'],
  },
  hum: {
    enMeaning: 'earth, ground, moist',
    etymology: 'Latin humus',
    origin: 'Latin',
    domains: ['earth'],
    overview_en: 'A root connecting earth and humility, from soil to human nature.',
    overview_zh: '连接土地和谦卑的词根，从土壤到人性。',
    originSummary_en: 'From Latin "humus" (earth, soil, ground).',
    originSummary_zh: '源自拉丁语 humus（土壤、泥土、大地）。',
    related: ['geo', 'cult', 'nat'],
  },
  it: {
    enMeaning: 'go, walk',
    etymology: 'Latin īre, itum',
    origin: 'Latin',
    domains: ['walking', 'movement'],
    overview_en: 'A compact Latin root for going, found in exit, transit, and circuit.',
    overview_zh: '简洁的拉丁行走词根，出现在 exit、transit 和 circuit 中。',
    originSummary_en: 'From Latin "īre" (to go) with past participle "itum".',
    originSummary_zh: '源自拉丁语 īre（走），过去分词 itum。',
    related: ['ced', 'vad', 'ven'],
  },
  jec: {
    enMeaning: 'throw, cast',
    etymology: 'Latin iacere, iactum',
    origin: 'Latin',
    domains: ['pushing'],
    overview_en:
      'A root about throwing and casting, forming words about projection, rejection, and injection.',
    overview_zh: '关于投掷和抛出的词根，构成关于投射、拒绝和注射的词汇。',
    originSummary_en: 'From Latin "iacere" (to throw) with forms jec-, ject-, jet-.',
    originSummary_zh: '源自拉丁语 iacere（投掷），形式有 jec-、ject-、jet-。',
    related: ['miss', 'pel', 'tra'],
  },
  jur: {
    enMeaning: 'law, right, swear',
    etymology: 'Latin iūs, iūris',
    origin: 'Latin',
    domains: ['law'],
    overview_en: 'A foundational root for legal vocabulary, from justice to jurisdiction.',
    overview_zh: '法律词汇的基础词根，从正义到司法管辖权。',
    originSummary_en: 'From Latin "iūs" (law, right) and "iūrāre" (to swear).',
    originSummary_zh: '源自拉丁语 iūs（法律、权利）和 iūrāre（宣誓）。',
    related: ['crim', 'lect', 'norm'],
  },
  lav: {
    enMeaning: 'wash, rinse',
    etymology: 'Latin lavāre',
    origin: 'Latin',
    domains: ['flowing'],
    overview_en: 'A root about washing, forming words about laundry, lavatories, and deluge.',
    overview_zh: '关于冲洗的词根，构成关于洗涤、盥洗室和洪水的词汇。',
    originSummary_en: 'From Latin "lavāre" (to wash, bathe).',
    originSummary_zh: '源自拉丁语 lavāre（洗涤、沐浴）。',
    related: ['flu', 'sol'],
  },
  lect: {
    enMeaning: 'choose, read, gather',
    etymology: 'Latin legere, lectum',
    origin: 'Latin',
    domains: ['choosing', 'knowledge'],
    overview_en:
      'A highly productive root covering choosing, reading, and gathering — from elect to intellect.',
    overview_zh: '高产词根，涵盖选择、阅读和收集——从选举到智力。',
    originSummary_en:
      'From Latin "legere" (to choose, gather, read) with past participle "lectum".',
    originSummary_zh: '源自拉丁语 legere（选择、收集、阅读），过去分词 lectum。',
    related: ['cern', 'dic', 'jur'],
  },
  light: {
    enMeaning: 'light, bright, not heavy',
    etymology: 'Old English lēoht / Latin lūx',
    origin: 'Old English',
    domains: ['light'],
    overview_en:
      'A Germanic root for light and brightness, forming words about illumination and levity.',
    overview_zh: '日耳曼词根，表示光亮和明亮，构成关于照明和轻快的词汇。',
    originSummary_en: 'From Old English "lēoht" (light, bright), cognate with Latin "lūx".',
    originSummary_zh: '源自古英语 lēoht（光、明亮），与拉丁语 lūx 同源。',
    related: ['cand', 'sol'],
  },
  loc: {
    enMeaning: 'place',
    etymology: 'Latin locus',
    origin: 'Latin',
    domains: ['position'],
    overview_en: 'A root about places and positions, from location to allocation.',
    overview_zh: '关于地点和位置的词根，从位置到分配。',
    originSummary_en: 'From Latin "locus" (place, position, spot).',
    originSummary_zh: '源自拉丁语 locus（地方、位置、处所）。',
    related: ['urb', 'dom', 'st'],
  },
  lud: {
    enMeaning: 'play, game',
    etymology: 'Latin lūdere',
    origin: 'Latin',
    domains: ['other'],
    overview_en:
      'A root about play and games, forming words about illusion, delusion, and elusiveness.',
    overview_zh: '关于游戏和玩耍的词根，构成关于幻觉、错觉和难以捉摸的词汇。',
    originSummary_en: 'From Latin "lūdere" (to play, mock, deceive).',
    originSummary_zh: '源自拉丁语 lūdere（玩耍、嘲弄、欺骗）。',
    related: ['sim', 'trop'],
  },
  main: {
    enMeaning: 'stay, dwell, remain',
    etymology: 'Latin manēre',
    origin: 'Latin',
    domains: ['standing'],
    overview_en:
      'A root about staying and remaining, forming words about permanence and maintenance.',
    overview_zh: '关于停留和保持的词根，构成关于持久和维护的词汇。',
    originSummary_en: 'From Latin "manēre" (to stay, remain, dwell).',
    originSummary_zh: '源自拉丁语 manēre（停留、保持、居住）。',
    related: ['tain', 'st', 'sit'],
  },
  maj: {
    enMeaning: 'great, large',
    etymology: 'Latin māior / magnus',
    origin: 'Latin',
    domains: ['size', 'amount'],
    overview_en: 'A root about greatness and size, from major to magnificent.',
    overview_zh: '关于伟大和大小的词根，从 major 到 magnificent。',
    originSummary_en: 'From Latin "māior" (greater) and "magnus" (great, large).',
    originSummary_zh: '源自拉丁语 māior（更大的）和 magnus（伟大的、大的）。',
    related: ['min', 'medi'],
  },
  man: {
    enMeaning: 'hand',
    etymology: 'Latin manus',
    origin: 'Latin',
    domains: ['body'],
    overview_en:
      'A fundamental root for hand, forming words about handling, manufacturing, and management.',
    overview_zh: '手的基础词根，构成关于操作、制造和管理的词汇。',
    originSummary_en: 'From Latin "manus" (hand).',
    originSummary_zh: '源自拉丁语 manus（手）。',
    related: ['tact', 'cap', 'gest'],
  },
  mand: {
    enMeaning: 'command, order, entrust',
    etymology: 'Latin mandāre',
    origin: 'Latin',
    domains: ['ordering', 'power'],
    overview_en: 'A root about commanding and entrusting, forming words about orders and demands.',
    overview_zh: '关于命令和委托的词根，构成关于指令和要求的词汇。',
    originSummary_en: 'From Latin "mandāre" (to command, entrust, commission).',
    originSummary_zh: '源自拉丁语 mandāre（命令、委托、委任）。',
    related: ['dom', 'jur', 'dic'],
  },
  mat: {
    enMeaning: 'ripe, mature',
    etymology: 'Latin mātūrus',
    origin: 'Latin',
    domains: ['change'],
    overview_en: 'A root about ripeness and maturity, forming words about growth and readiness.',
    overview_zh: '关于成熟和到期的词根，构成关于生长和就绪的词汇。',
    originSummary_en: 'From Latin "mātūrus" (ripe, mature, timely).',
    originSummary_zh: '源自拉丁语 mātūrus（成熟的、到期的、及时的）。',
    related: ['gen', 'nat', 'nov'],
  },
  medi: {
    enMeaning: 'middle, heal',
    etymology: 'Latin medius / medicus',
    origin: 'Latin',
    domains: ['health', 'position'],
    overview_en: 'A dual-meaning root: "middle" from medius and "healing" from medicus.',
    overview_zh: '双义词根：来自 medius 的"中间"和来自 medicus 的"治疗"。',
    originSummary_en: 'From Latin "medius" (middle) and "medicus" (healer, physician).',
    originSummary_zh: '源自拉丁语 medius（中间的）和 medicus（治疗者、医生）。',
    related: ['min', 'maj', 'par'],
  },
  merg: {
    enMeaning: 'sink, dip, plunge',
    etymology: 'Latin mergere',
    origin: 'Latin',
    domains: ['movement', 'flowing'],
    overview_en: 'A root about sinking and immersion, forming words about merging and submerging.',
    overview_zh: '关于沉没和浸没的词根，构成关于合并和淹没的词汇。',
    originSummary_en: 'From Latin "mergere" (to dip, sink, immerse).',
    originSummary_zh: '源自拉丁语 mergere（浸、沉、淹没）。',
    related: ['flu', 'solv'],
  },
  migr: {
    enMeaning: 'move, change place',
    etymology: 'Latin migrāre',
    origin: 'Latin',
    domains: ['movement'],
    overview_en: 'A root about changing places, forming words about migration and immigration.',
    overview_zh: '关于迁移的词根，构成关于移民和迁徙的词汇。',
    originSummary_en: 'From Latin "migrāre" (to change one\'s residence, move).',
    originSummary_zh: '源自拉丁语 migrāre（搬迁、迁移）。',
    related: ['mov', 'vad', 'it'],
  },
  min: {
    enMeaning: 'small, tiny, lessen',
    etymology: 'Latin minor / minuere',
    origin: 'Latin',
    domains: ['size'],
    overview_en: 'A root about smallness and reduction, from minute to diminish.',
    overview_zh: '关于微小和减少的词根，从 minute 到 diminish。',
    originSummary_en: 'From Latin "minor" (smaller) and "minuere" (to lessen).',
    originSummary_zh: '源自拉丁语 minor（较小的）和 minuere（减少）。',
    related: ['maj', 'medi'],
  },
  miss: {
    enMeaning: 'send, throw, let go',
    etymology: 'Latin mittere, missum',
    origin: 'Latin',
    domains: ['sending'],
    overview_en:
      'A major root about sending, forming words about missions, messages, and emissions.',
    overview_zh: '关于发送的主要词根，构成关于任务、消息和排放的词汇。',
    originSummary_en: 'From Latin "mittere" (to send, let go) with past participle "missum".',
    originSummary_zh: '源自拉丁语 mittere（发送、放走），过去分词 missum。',
    related: ['jec', 'pel', 'dit'],
  },
  mon: {
    enMeaning: 'warn, remind, advise',
    etymology: 'Latin monēre',
    origin: 'Latin',
    domains: ['speech', 'knowledge'],
    overview_en:
      'A root about warning and advising, forming words about monuments, monitors, and admonitions.',
    overview_zh: '关于警告和建议的词根，构成关于纪念碑、监视器和训诫的词汇。',
    originSummary_en: 'From Latin "monēre" (to warn, advise, remind).',
    originSummary_zh: '源自拉丁语 monēre（警告、建议、提醒）。',
    related: ['dic', 'monstr', 'mand'],
  },
  monstr: {
    enMeaning: 'show, point out, warn',
    etymology: 'Latin monstrāre',
    origin: 'Latin',
    domains: ['seeing'],
    overview_en: 'A root about showing and demonstrating, from demonstrate to monster.',
    overview_zh: '关于展示和证明的词根，从 demonstrate 到 monster。',
    originSummary_en: 'From Latin "monstrāre" (to show, point out) related to "monēre" (to warn).',
    originSummary_zh: '源自拉丁语 monstrāre（展示、指出），与 monēre（警告）相关。',
    related: ['mon', 'vis', 'spec'],
  },
  mort: {
    enMeaning: 'death',
    etymology: 'Latin mors, mortis',
    origin: 'Latin',
    domains: ['death'],
    overview_en:
      'A root about death and mortality, forming words about mortgages, immortality, and mortuaries.',
    overview_zh: '关于死亡和有限寿命的词根，构成关于抵押、不朽和太平间的词汇。',
    originSummary_en: 'From Latin "mors" (death) with stem "mort-".',
    originSummary_zh: '源自拉丁语 mors（死亡），词干 mort-。',
    related: ['viv', 'cid', 'nat'],
  },
  mov: {
    enMeaning: 'move',
    etymology: 'Latin movēre',
    origin: 'Latin',
    domains: ['movement'],
    overview_en: 'A central root for motion, from physical movement to emotional motivation.',
    overview_zh: '运动的核心词根，从身体运动到情感动机。',
    originSummary_en: 'From Latin "movēre" (to move) with variants mob-, mot-.',
    originSummary_zh: '源自拉丁语 movēre（移动），变体有 mob-、mot-。',
    related: ['ven', 'ced', 'pel'],
  },
  nat: {
    enMeaning: 'born, birth, nature',
    etymology: 'Latin nāscī, nātus',
    origin: 'Latin',
    domains: ['birth', 'nature'],
    overview_en: 'A root about birth and nature, from nations to natural phenomena.',
    overview_zh: '关于出生和自然的词根，从国家到自然现象。',
    originSummary_en: 'From Latin "nāscī" (to be born), past participle "nātus".',
    originSummary_zh: '源自拉丁语 nāscī（出生），过去分词 nātus。',
    related: ['gen', 'ori', 'bio'],
  },
  nav: {
    enMeaning: 'ship, sail',
    etymology: 'Latin nāvis',
    origin: 'Latin',
    domains: ['transport'],
    overview_en:
      'A root about ships and sailing, forming words about navigation and naval operations.',
    overview_zh: '关于船和航行的词根，构成关于导航和海军作战的词汇。',
    originSummary_en: 'From Latin "nāvis" (ship) and "nāvigāre" (to sail).',
    originSummary_zh: '源自拉丁语 nāvis（船）和 nāvigāre（航行）。',
    related: ['aster', 'port'],
  },
  nom: {
    enMeaning: 'law, custom, manage',
    etymology: 'Greek nomos (νόμος)',
    origin: 'Greek',
    domains: ['law'],
    overview_en: 'A Greek root about law and management, from economy to astronomy.',
    overview_zh: '希腊词根，关于法则和管理，从经济学到天文学。',
    originSummary_en: 'From Greek "nomos" (law, custom, usage).',
    originSummary_zh: '源自希腊语 nomos（法则、习俗、惯例）。',
    related: ['nomin', 'jur', 'norm'],
  },
  nomin: {
    enMeaning: 'name',
    etymology: 'Latin nōmen',
    origin: 'Latin',
    domains: ['speech'],
    overview_en:
      'A root about naming, forming words about nomination, denomination, and nomenclature.',
    overview_zh: '关于命名的词根，构成关于提名、面额和命名法的词汇。',
    originSummary_en: 'From Latin "nōmen" (name).',
    originSummary_zh: '源自拉丁语 nōmen（名字）。',
    related: ['nom', 'dic', 'claim'],
  },
  norm: {
    enMeaning: 'rule, standard, pattern',
    etymology: 'Latin norma',
    origin: 'Latin',
    domains: ['law', 'other'],
    overview_en: 'A root about standards and rules, forming words about normalcy and norms.',
    overview_zh: '关于标准和规范的词根，构成关于正常和准则的词汇。',
    originSummary_en: 'From Latin "norma" (carpenter\'s square, rule, pattern).',
    originSummary_zh: '源自拉丁语 norma（木匠的直角尺、规则、模式）。',
    related: ['jur', 'mand'],
  },
  nour: {
    enMeaning: 'feed, nourish',
    etymology: 'Latin nūtrīre',
    origin: 'Latin',
    domains: ['food'],
    overview_en: 'A root about feeding and nurturing, forming words about nutrition and growth.',
    overview_zh: '关于喂养和滋养的词根，构成关于营养和生长的词汇。',
    originSummary_en: 'From Latin "nūtrīre" (to feed, nourish, sustain).',
    originSummary_zh: '源自拉丁语 nūtrīre（喂养、滋养、维持）。',
    related: ['viv', 'nat', 'carn'],
  },
  nov: {
    enMeaning: 'new',
    etymology: 'Latin novus',
    origin: 'Latin',
    domains: ['change'],
    overview_en: 'A root about newness, forming words about innovation and renovation.',
    overview_zh: '关于新的词根，构成关于创新和翻新的词汇。',
    originSummary_en: 'From Latin "novus" (new, young, fresh).',
    originSummary_zh: '源自拉丁语 novus（新的、年轻的、新鲜的）。',
    related: ['gen', 'ori', 'mat'],
  },
  ori: {
    enMeaning: 'rise, begin, source',
    etymology: 'Latin orīrī',
    origin: 'Latin',
    domains: ['birth', 'movement'],
    overview_en: 'A root about rising and beginning, from origins to orientation.',
    overview_zh: '关于升起和起源的词根，从起源到定向。',
    originSummary_en: 'From Latin "orīrī" (to rise, appear, be born).',
    originSummary_zh: '源自拉丁语 orīrī（升起、出现、诞生）。',
    related: ['nat', 'gen', 'sol'],
  },
  par: {
    enMeaning: 'equal',
    etymology: 'Latin pār',
    origin: 'Latin',
    domains: ['other'],
    overview_en: 'A root about equality and comparison, from parity to disparity.',
    overview_zh: '关于平等和比较的词根，从平等到差距。',
    originSummary_en: 'From Latin "pār" (equal, like, matching).',
    originSummary_zh: '源自拉丁语 pār（相等的、类似的）。',
    related: ['sim', 'norm'],
    grimm: 'b/p/f/v',
  },
  part: {
    enMeaning: 'part, divide, share',
    etymology: 'Latin pars, partis',
    origin: 'Latin',
    domains: ['other'],
    overview_en:
      'A root about parts and division, forming words about participation and departure.',
    overview_zh: '关于部分和分割的词根，构成关于参与和离开的词汇。',
    originSummary_en: 'From Latin "pars" (part, piece, share) with stem "part-".',
    originSummary_zh: '源自拉丁语 pars（部分、片段、份额），词干 part-。',
    related: ['cid', 'tail'],
    grimm: 'b/p/f/v',
  },
  path: {
    enMeaning: 'feeling, suffering, disease',
    etymology: 'Greek pathos (πάθος)',
    origin: 'Greek',
    domains: ['emotion', 'health'],
    overview_en: 'A Greek root about feeling and suffering, from empathy to pathology.',
    overview_zh: '希腊词根，关于感受和痛苦，从共情到病理学。',
    originSummary_en: 'From Greek "pathos" (suffering, feeling, experience).',
    originSummary_zh: '源自希腊语 pathos（痛苦、感受、经历）。',
    related: ['anim', 'am'],
    grimm: 'b/p/f/v',
  },
  patr: {
    enMeaning: 'father',
    etymology: 'Latin pater / Greek patḗr',
    origin: 'Latin',
    domains: ['society'],
    overview_en: 'A root about fathers and fatherhood, from patriarchs to patriotism.',
    overview_zh: '关于父亲和父权的词根，从族长到爱国主义。',
    originSummary_en: 'From Latin "pater" and Greek "patḗr" (father).',
    originSummary_zh: '源自拉丁语 pater 和希腊语 patḗr（父亲）。',
    related: ['nat', 'gen', 'dom'],
    grimm: 'b/p/f/v',
  },
  ped: {
    enMeaning: 'foot',
    etymology: 'Latin pēs, pedis',
    origin: 'Latin',
    domains: ['body', 'walking'],
    overview_en: 'A root about feet and walking, from pedestrian to expedition.',
    overview_zh: '关于脚和步行的词根，从行人到探险。',
    originSummary_en: 'From Latin "pēs" (foot) with stem "ped-".',
    originSummary_zh: '源自拉丁语 pēs（脚），词干 ped-。',
    related: ['it', 'ced', 'vad'],
    grimm: 'b/p/f/v',
  },
  pel: {
    enMeaning: 'push, drive',
    etymology: 'Latin pellere',
    origin: 'Latin',
    domains: ['pushing'],
    overview_en:
      'A root about pushing and driving, forming words about compulsion, repulsion, and appeal.',
    overview_zh: '关于推动和驱动的词根，构成关于强制、排斥和呼吁的词汇。',
    originSummary_en: 'From Latin "pellere" (to push, drive) with past participle "pulsum".',
    originSummary_zh: '源自拉丁语 pellere（推、驱动），过去分词 pulsum。',
    related: ['mov', 'press', 'jec'],
    grimm: 'b/p/f/v',
  },
  peri: {
    enMeaning: 'try, test, experience',
    etymology: 'Latin perīrī / Greek peira',
    origin: 'Latin',
    domains: ['knowledge'],
    overview_en: 'A root about testing and experience, from experiment to expert.',
    overview_zh: '关于尝试和经验的词根，从实验到专家。',
    originSummary_en: 'From Latin "perīrī" (to try, test) and Greek "peira" (trial, experience).',
    originSummary_zh: '源自拉丁语 perīrī（尝试、测试）和希腊语 peira（试验、经验）。',
    related: ['cern', 'spec'],
    grimm: 'b/p/f/v',
  },
  person: {
    enMeaning: 'person, mask',
    etymology: 'Latin persōna',
    origin: 'Latin',
    domains: ['society'],
    overview_en: 'A root about persons and roles, originally from theatrical masks.',
    overview_zh: '关于人和角色的词根，最初来自戏剧面具。',
    originSummary_en: 'From Latin "persōna" (mask, character, person).',
    originSummary_zh: '源自拉丁语 persōna（面具、角色、人物）。',
    related: ['hospit', 'nat'],
    grimm: 'b/p/f/v',
  },
  pet: {
    enMeaning: 'seek, strive, aim',
    etymology: 'Latin petere',
    origin: 'Latin',
    domains: ['movement'],
    overview_en: 'A root about seeking and striving, forming words about competition and appetite.',
    overview_zh: '关于寻求和奋斗的词根，构成关于竞争和欲望的词汇。',
    originSummary_en: 'From Latin "petere" (to seek, aim at, rush at).',
    originSummary_zh: '源自拉丁语 petere（寻求、瞄准、冲向）。',
    related: ['cap', 'ven'],
    grimm: 'b/p/f/v',
  },
  ple: {
    enMeaning: 'fill, full',
    etymology: 'Latin plēre / plēnus',
    origin: 'Latin',
    domains: ['amount'],
    overview_en: 'A root about fullness, forming words about completion, plenty, and supply.',
    overview_zh: '关于充满的词根，构成关于完成、丰富和供应的词汇。',
    originSummary_en: 'From Latin "plēre" (to fill) and "plēnus" (full).',
    originSummary_zh: '源自拉丁语 plēre（充满）和 plēnus（满的）。',
    related: ['sat', 'vac'],
    grimm: 'b/p/f/v',
  },
  plod: {
    enMeaning: 'burst, clap',
    etymology: 'Latin plaudere / explōdere',
    origin: 'Latin',
    domains: ['sound', 'action'],
    overview_en: 'A root about bursting and applause, from explosions to plausible arguments.',
    overview_zh: '关于爆破和鼓掌的词根，从爆炸到合理的论点。',
    originSummary_en: 'From Latin "plaudere" (to clap) and "explōdere" (to drive out by clapping).',
    originSummary_zh: '源自拉丁语 plaudere（鼓掌）和 explōdere（通过鼓掌赶出）。',
    related: ['pel', 'claim'],
    grimm: 'b/p/f/v',
  },
  port: {
    enMeaning: 'carry, harbor',
    etymology: 'Latin portāre',
    origin: 'Latin',
    domains: ['transport'],
    overview_en: 'A major root for carrying and harbors, one of the most common in English.',
    overview_zh: '主要的搬运和港口词根，是英语中最常见的词根之一。',
    originSummary_en: 'From Latin "portāre" (to carry) and "portus" (harbor).',
    originSummary_zh: '源自拉丁语 portāre（搬运）和 portus（港口）。',
    related: ['fer', 'car', 'gest'],
    grimm: 'b/p/f/v',
  },
  press: {
    enMeaning: 'press, push',
    etymology: 'Latin premere, pressum',
    origin: 'Latin',
    domains: ['pressing'],
    overview_en:
      'A root about pressing and pushing, forming words about pressure, expression, and impression.',
    overview_zh: '关于按压和推动的词根，构成关于压力、表达和印象的词汇。',
    originSummary_en: 'From Latin "premere" (to press) with past participle "pressum".',
    originSummary_zh: '源自拉丁语 premere（按压），过去分词 pressum。',
    related: ['pel', 'strain', 'forc'],
    grimm: 'b/p/f/v',
  },
  pric: {
    enMeaning: 'value, worth, price',
    etymology: 'Latin pretium',
    origin: 'Latin',
    domains: ['other'],
    overview_en: 'A root about value and worth, from price to appreciation.',
    overview_zh: '关于价值和价格的词根，从价格到欣赏。',
    originSummary_en: 'From Latin "pretium" (price, value, reward).',
    originSummary_zh: '源自拉丁语 pretium（价格、价值、奖赏）。',
    related: ['val', 'peri'],
    grimm: 'b/p/f/v',
  },
  pun: {
    enMeaning: 'punish, penalty',
    etymology: 'Latin pūnīre / poena',
    origin: 'Latin',
    domains: ['law'],
    overview_en: 'A root about punishment and penalties, from punitive to impunity.',
    overview_zh: '关于惩罚和处罚的词根，从惩罚性到免罚。',
    originSummary_en: 'From Latin "pūnīre" (to punish) and "poena" (penalty, punishment).',
    originSummary_zh: '源自拉丁语 pūnīre（惩罚）和 poena（刑罚）。',
    related: ['crim', 'jur'],
    grimm: 'b/p/f/v',
  },
  quaint: {
    enMeaning: 'know, recognize',
    etymology: 'Latin cognōscere',
    origin: 'Latin',
    domains: ['knowledge'],
    overview_en: 'A root about knowing and recognizing, from acquaint to quaint.',
    overview_zh: '关于了解和认识的词根，从 acquaint 到 quaint。',
    originSummary_en: 'From Latin "cognōscere" (to get to know) via Old French "cointe".',
    originSummary_zh: '源自拉丁语 cognōscere（认识）经由古法语 cointe。',
    related: ['cern', 'lect'],
  },
  rot: {
    enMeaning: 'wheel, turn',
    etymology: 'Latin rota',
    origin: 'Latin',
    domains: ['turning'],
    overview_en: 'A root about wheels and rotation, from rotary to routine.',
    overview_zh: '关于轮子和旋转的词根，从旋转的到日常。',
    originSummary_en: 'From Latin "rota" (wheel) and "rotāre" (to turn).',
    originSummary_zh: '源自拉丁语 rota（轮子）和 rotāre（旋转）。',
    related: ['circ', 'vers', 'trop'],
  },
  rud: {
    enMeaning: 'raw, rough, primitive',
    etymology: 'Latin rudis',
    origin: 'Latin',
    domains: ['other'],
    overview_en: 'A root about rawness and roughness, from rude to erudite.',
    overview_zh: '关于粗糙和原始的词根，从粗鲁到博学。',
    originSummary_en: 'From Latin "rudis" (rough, raw, unformed).',
    originSummary_zh: '源自拉丁语 rudis（粗糙的、未加工的）。',
    related: ['nat', 'nov'],
  },
  sat: {
    enMeaning: 'enough, full, satisfy',
    etymology: 'Latin satis / saturāre',
    origin: 'Latin',
    domains: ['amount'],
    overview_en: 'A root about satisfaction and fullness, from satiate to insatiable.',
    overview_zh: '关于满足和饱足的词根，从使满足到不知足。',
    originSummary_en: 'From Latin "satis" (enough) and "saturāre" (to fill, satisfy).',
    originSummary_zh: '源自拉丁语 satis（足够）和 saturāre（充满、满足）。',
    related: ['ple', 'min', 'maj'],
  },
  serv: {
    enMeaning: 'serve, keep, save',
    etymology: 'Latin servāre / servīre',
    origin: 'Latin',
    domains: ['action'],
    overview_en: 'A root about serving and keeping, from service to preservation.',
    overview_zh: '关于服务和保存的词根，从服务到保存。',
    originSummary_en: 'From Latin "servāre" (to keep, save) and "servīre" (to serve).',
    originSummary_zh: '源自拉丁语 servāre（保持、保存）和 servīre（服务）。',
    related: ['tain', 'main'],
  },
  sim: {
    enMeaning: 'like, similar, same',
    etymology: 'Latin similis',
    origin: 'Latin',
    domains: ['similarity'],
    overview_en:
      'A root about likeness and sameness, forming words about simulation and resemblance.',
    overview_zh: '关于相似和相同的词根，构成关于模拟和相似的词汇。',
    originSummary_en: 'From Latin "similis" (like, similar) and "simul" (at the same time).',
    originSummary_zh: '源自拉丁语 similis（相似的）和 simul（同时）。',
    related: ['par', 'uni'],
  },
  sit: {
    enMeaning: 'sit, settle, place',
    etymology: 'Latin sedēre / sīdere',
    origin: 'Latin',
    domains: ['sitting'],
    overview_en: 'A major root about sitting and settling, from president to reside.',
    overview_zh: '关于坐和安置的主要词根，从总统到居住。',
    originSummary_en:
      'From Latin "sedēre" (to sit) and "sīdere" (to settle) with variants sid-, sed-, sess-.',
    originSummary_zh: '源自拉丁语 sedēre（坐）和 sīdere（安顿），变体有 sid-、sed-、sess-。',
    related: ['st', 'loc', 'main'],
  },
  sol: {
    enMeaning: 'alone, sun, whole',
    etymology: 'Latin sōlus / sōl',
    origin: 'Latin',
    domains: ['light', 'other'],
    overview_en: 'A multi-meaning root: alone (sōlus), sun (sōl), and solid (solidus).',
    overview_zh: '多义词根：单独（sōlus）、太阳（sōl）和坚固（solidus）。',
    originSummary_en: 'From Latin "sōlus" (alone), "sōl" (sun), and "solidus" (solid, whole).',
    originSummary_zh: '源自拉丁语 sōlus（单独的）、sōl（太阳）和 solidus（坚固的）。',
    related: ['uni', 'light', 'aster'],
  },
  solv: {
    enMeaning: 'loosen, dissolve, free',
    etymology: 'Latin solvere',
    origin: 'Latin',
    domains: ['change'],
    overview_en: 'A root about loosening and freeing, from solve to dissolve.',
    overview_zh: '关于松开和释放的词根，从解决到溶解。',
    originSummary_en: 'From Latin "solvere" (to loosen, untie, dissolve).',
    originSummary_zh: '源自拉丁语 solvere（松开、解开、溶解）。',
    related: ['strain', 'flu'],
  },
  son: {
    enMeaning: 'sound',
    etymology: 'Latin sonus',
    origin: 'Latin',
    domains: ['sound'],
    overview_en: 'A root about sound, forming words about resonance, harmony, and acoustics.',
    overview_zh: '关于声音的词根，构成关于共鸣、和谐和声学的词汇。',
    originSummary_en: 'From Latin "sonus" (sound) and "sonāre" (to sound).',
    originSummary_zh: '源自拉丁语 sonus（声音）和 sonāre（发声）。',
    related: ['voc', 'claim'],
  },
  spec: {
    enMeaning: 'look, see, observe',
    etymology: 'Latin specere',
    origin: 'Latin',
    domains: ['seeing'],
    overview_en: 'A major root about seeing and observing, from spectacle to perspective.',
    overview_zh: '关于看和观察的主要词根，从奇观到视角。',
    originSummary_en: 'From Latin "specere" (to look at) with variants spic-, spect-.',
    originSummary_zh: '源自拉丁语 specere（看），变体有 spic-、spect-。',
    related: ['vis', 'monstr'],
  },
  spir: {
    enMeaning: 'breathe',
    etymology: 'Latin spīrāre',
    origin: 'Latin',
    domains: ['breathing'],
    overview_en: 'A root about breathing, forming words about inspiration, aspiration, and spirit.',
    overview_zh: '关于呼吸的词根，构成关于灵感、志向和精神的词汇。',
    originSummary_en: 'From Latin "spīrāre" (to breathe) and "spīritus" (breath, spirit).',
    originSummary_zh: '源自拉丁语 spīrāre（呼吸）和 spīritus（呼吸、精神）。',
    related: ['anim', 'viv'],
  },
  st: {
    enMeaning: 'stand, set, place',
    etymology: 'Latin stāre / sistere',
    origin: 'Latin',
    domains: ['standing'],
    overview_en:
      'The most prolific root family in English, about standing, establishing, and states of being.',
    overview_zh: '英语中最高产的词根家族，关于站立、建立和存在状态。',
    originSummary_en:
      'From Latin "stāre" (to stand), "sistere" (to cause to stand), with stem "stat-".',
    originSummary_zh: '源自拉丁语 stāre（站立）、sistere（使站立），词干 stat-。',
    related: ['sit', 'loc', 'main'],
  },
  stinct: {
    enMeaning: 'prick, goad, urge',
    etymology: 'Latin stinguere',
    origin: 'Latin',
    domains: ['action'],
    overview_en: 'A root about pricking and urging, from instinct to distinction.',
    overview_zh: '关于刺激和驱策的词根，从本能到区分。',
    originSummary_en: 'From Latin "stinguere" (to prick, quench, mark) with variant "stimulāre".',
    originSummary_zh: '源自拉丁语 stinguere（刺、熄灭、标记），变体 stimulāre。',
    related: ['cern', 'pel'],
  },
  strain: {
    enMeaning: 'bind, draw tight',
    etymology: 'Latin stringere',
    origin: 'Latin',
    domains: ['binding'],
    overview_en:
      'A root about tightening and binding, forming words about restriction, stress, and constraint.',
    overview_zh: '关于绷紧和束缚的词根，构成关于限制、压力和约束的词汇。',
    originSummary_en:
      'From Latin "stringere" (to draw tight, bind) with variants strict-, stress-, string-.',
    originSummary_zh: '源自拉丁语 stringere（拉紧、束缚），变体有 strict-、stress-、string-。',
    related: ['press', 'her', 'tain'],
  },
  tact: {
    enMeaning: 'touch',
    etymology: 'Latin tangere, tactum',
    origin: 'Latin',
    domains: ['other'],
    overview_en: 'A root about touch and contact, from tangible to contagious.',
    overview_zh: '关于接触和触碰的词根，从有形的到有传染性的。',
    originSummary_en: 'From Latin "tangere" (to touch) with past participle "tactum".',
    originSummary_zh: '源自拉丁语 tangere（触碰），过去分词 tactum。',
    related: ['man', 'her'],
    grimm: 'd/t/s/z',
  },
  tail: {
    enMeaning: 'cut',
    etymology: 'Latin tāliāre',
    origin: 'Latin',
    domains: ['cutting'],
    overview_en: 'A root about cutting, forming words about detail, retail, and tailoring.',
    overview_zh: '关于切割的词根，构成关于细节、零售和裁剪的词汇。',
    originSummary_en: 'From Latin "tāliāre" (to cut) via Old French "taillier".',
    originSummary_zh: '源自拉丁语 tāliāre（切割）经由古法语 taillier。',
    related: ['cid', 'part'],
    grimm: 'd/t/s/z',
  },
  tain: {
    enMeaning: 'hold, keep, have',
    etymology: 'Latin tenēre',
    origin: 'Latin',
    domains: ['holding'],
    overview_en: 'A major root about holding and keeping, from maintain to sustain.',
    overview_zh: '关于持有和保持的主要词根，从维持到支撑。',
    originSummary_en: 'From Latin "tenēre" (to hold, keep) with variants ten-, tin-, tent-.',
    originSummary_zh: '源自拉丁语 tenēre（持有、保持），变体有 ten-、tin-、tent-。',
    related: ['cap', 'her', 'serv'],
    grimm: 'd/t/s/z',
  },
  tort: {
    enMeaning: 'twist, turn, wrench',
    etymology: 'Latin torquēre, tortum',
    origin: 'Latin',
    domains: ['turning'],
    overview_en: 'A root about twisting and turning, from torture to distortion.',
    overview_zh: '关于扭曲和旋转的词根，从酷刑到歪曲。',
    originSummary_en: 'From Latin "torquēre" (to twist, wrench) with past participle "tortum".',
    originSummary_zh: '源自拉丁语 torquēre（扭、拧），过去分词 tortum。',
    related: ['vers', 'trop', 'strain'],
    grimm: 'd/t/s/z',
  },
  tra: {
    enMeaning: 'pull, drag, draw',
    etymology: 'Latin trahere, tractum',
    origin: 'Latin',
    domains: ['pulling'],
    overview_en: 'A major root about pulling and drawing, from attract to abstract.',
    overview_zh: '关于拉和拽的主要词根，从吸引到抽象。',
    originSummary_en: 'From Latin "trahere" (to pull, drag, draw) with past participle "tractum".',
    originSummary_zh: '源自拉丁语 trahere（拉、拽、牵引），过去分词 tractum。',
    related: ['pel', 'strain', 'cap'],
    grimm: 'd/t/s/z',
  },
  trem: {
    enMeaning: 'tremble, shake',
    etymology: 'Latin tremere',
    origin: 'Latin',
    domains: ['movement'],
    overview_en: 'A root about trembling and shaking, from tremendous to tremor.',
    overview_zh: '关于颤抖和震动的词根，从巨大的到震颤。',
    originSummary_en: 'From Latin "tremere" (to tremble, shake, quake).',
    originSummary_zh: '源自拉丁语 tremere（颤抖、震动、发抖）。',
    related: ['turb', 'mov'],
    grimm: 'd/t/s/z',
  },
  trop: {
    enMeaning: 'turn, change',
    etymology: 'Greek tropos (τρόπος)',
    origin: 'Greek',
    domains: ['turning'],
    overview_en: 'A Greek root about turning and change, from tropic to entropy.',
    overview_zh: '希腊词根，关于转向和变化，从热带到熵。',
    originSummary_en: 'From Greek "tropos" (turn, direction, way).',
    originSummary_zh: '源自希腊语 tropos（转、方向、方式）。',
    related: ['vers', 'rot', 'circ'],
    grimm: 'd/t/s/z',
  },
  turb: {
    enMeaning: 'stir up, disturb',
    etymology: 'Latin turbāre',
    origin: 'Latin',
    domains: ['movement'],
    overview_en: 'A root about stirring and disturbing, from trouble to turbulence.',
    overview_zh: '关于搅动和扰乱的词根，从麻烦到湍流。',
    originSummary_en: 'From Latin "turbāre" (to disturb, confuse) from "turba" (crowd, commotion).',
    originSummary_zh: '源自拉丁语 turbāre（打扰、混乱），来自 turba（人群、骚动）。',
    related: ['trem', 'mov'],
    grimm: 'd/t/s/z',
  },
  uni: {
    enMeaning: 'one, whole',
    etymology: 'Latin ūnus',
    origin: 'Latin',
    domains: ['number'],
    overview_en: 'A root about oneness and wholeness, from unit to universal.',
    overview_zh: '关于一和整体的词根，从单位到普遍的。',
    originSummary_en: 'From Latin "ūnus" (one) and "ūnīre" (to unite).',
    originSummary_zh: '源自拉丁语 ūnus（一）和 ūnīre（统一）。',
    related: ['sol', 'sim'],
  },
  urb: {
    enMeaning: 'city',
    etymology: 'Latin urbs',
    origin: 'Latin',
    domains: ['society'],
    overview_en: 'A root about cities, forming words about urban life and civilization.',
    overview_zh: '关于城市的词根，构成关于城市生活和文明的词汇。',
    originSummary_en: 'From Latin "urbs" (city, walled town).',
    originSummary_zh: '源自拉丁语 urbs（城市、城镇）。',
    related: ['loc', 'dom'],
  },
  util: {
    enMeaning: 'use',
    etymology: 'Latin ūtī',
    origin: 'Latin',
    domains: ['action'],
    overview_en: 'A root about use and utility, from utilize to utensil.',
    overview_zh: '关于使用和效用的词根，从利用到器具。',
    originSummary_en:
      'From Latin "ūtī" (to use) with forms "ūtilis" (useful) and "ūtēnsilis" (fit for use).',
    originSummary_zh: '源自拉丁语 ūtī（使用），形式有 ūtilis（有用的）和 ūtēnsilis（适用的）。',
    related: ['fac', 'serv'],
  },
  vac: {
    enMeaning: 'empty',
    etymology: 'Latin vacuus',
    origin: 'Latin',
    domains: ['other'],
    overview_en: 'A root about emptiness, forming words about vacation, vacuum, and vanity.',
    overview_zh: '关于空的词根，构成关于假期、真空和虚荣的词汇。',
    originSummary_en: 'From Latin "vacuus" (empty) and "vacāre" (to be empty, free).',
    originSummary_zh: '源自拉丁语 vacuus（空的）和 vacāre（空闲）。',
    related: ['ple', 'sat'],
  },
  vad: {
    enMeaning: 'go, walk',
    etymology: 'Latin vādere',
    origin: 'Latin',
    domains: ['walking', 'movement'],
    overview_en: 'A root about going and walking, forming words about invasion and evasion.',
    overview_zh: '关于行走和前进的词根，构成关于入侵和逃避的词汇。',
    originSummary_en: 'From Latin "vādere" (to go, walk, advance).',
    originSummary_zh: '源自拉丁语 vādere（走、行进、前进）。',
    related: ['ced', 'it', 'ven'],
  },
  val: {
    enMeaning: 'strong, worth, value',
    etymology: 'Latin valēre',
    origin: 'Latin',
    domains: ['strength', 'power'],
    overview_en: 'A root about strength and worth, from value to prevalent.',
    overview_zh: '关于力量和价值的词根，从价值到普遍的。',
    originSummary_en: 'From Latin "valēre" (to be strong, be worth).',
    originSummary_zh: '源自拉丁语 valēre（强壮、有价值）。',
    related: ['forc', 'pric'],
  },
  ven: {
    enMeaning: 'come',
    etymology: 'Latin venīre',
    origin: 'Latin',
    domains: ['movement'],
    overview_en: 'A root about coming, forming words about events, conventions, and adventures.',
    overview_zh: '关于来的词根，构成关于事件、会议和冒险的词汇。',
    originSummary_en: 'From Latin "venīre" (to come) with past participle "ventum".',
    originSummary_zh: '源自拉丁语 venīre（来），过去分词 ventum。',
    related: ['ced', 'vad', 'it'],
  },
  vers: {
    enMeaning: 'turn, change',
    etymology: 'Latin vertere',
    origin: 'Latin',
    domains: ['turning'],
    overview_en: 'A major root about turning and change, from universe to controversy.',
    overview_zh: '关于转变和变化的主要词根，从宇宙到争议。',
    originSummary_en: 'From Latin "vertere" (to turn) with past participle "versum".',
    originSummary_zh: '源自拉丁语 vertere（转），过去分词 versum。',
    related: ['trop', 'rot', 'tort'],
  },
  vinc: {
    enMeaning: 'conquer, overcome',
    etymology: 'Latin vincere',
    origin: 'Latin',
    domains: ['power'],
    overview_en: 'A root about conquering and overcoming, from victory to invincible.',
    overview_zh: '关于征服和克服的词根，从胜利到不可战胜。',
    originSummary_en: 'From Latin "vincere" (to conquer, overcome) with past participle "victum".',
    originSummary_zh: '源自拉丁语 vincere（征服、克服），过去分词 victum。',
    related: ['forc', 'val'],
  },
  vis: {
    enMeaning: 'see',
    etymology: 'Latin vidēre, vīsum',
    origin: 'Latin',
    domains: ['seeing'],
    overview_en: 'A fundamental root about seeing and vision, one of the most common in English.',
    overview_zh: '关于看和视觉的基础词根，是英语中最常见的词根之一。',
    originSummary_en:
      'From Latin "vidēre" (to see) with past participle "vīsum" and variants vid-.',
    originSummary_zh: '源自拉丁语 vidēre（看），过去分词 vīsum，变体有 vid-。',
    related: ['spec', 'monstr'],
  },
  viv: {
    enMeaning: 'live, life',
    etymology: 'Latin vīvere',
    origin: 'Latin',
    domains: ['life'],
    overview_en: 'A root about living, forming words about vitality, vividity, and survival.',
    overview_zh: '关于活着的词根，构成关于活力、生动和生存的词汇。',
    originSummary_en: 'From Latin "vīvere" (to live) with variants vit-, vig-, veg-.',
    originSummary_zh: '源自拉丁语 vīvere（活），变体有 vit-、vig-、veg-。',
    related: ['bio', 'anim', 'spir'],
  },
  voc: {
    enMeaning: 'voice, call',
    etymology: 'Latin vōx, vōcis',
    origin: 'Latin',
    domains: ['speech', 'sound'],
    overview_en: 'A root about voice and calling, from vocabulary to advocacy.',
    overview_zh: '关于声音和呼唤的词根，从词汇到倡导。',
    originSummary_en: 'From Latin "vōx" (voice) and "vocāre" (to call).',
    originSummary_zh: '源自拉丁语 vōx（声音）和 vocāre（呼唤）。',
    related: ['claim', 'dic', 'son'],
  },
  vol: {
    enMeaning: 'roll, turn, wish',
    etymology: 'Latin volvere / voluntās',
    origin: 'Latin',
    domains: ['turning', 'movement'],
    overview_en: 'A root about rolling and willing, from evolution to volunteer.',
    overview_zh: '关于滚动和意愿的词根，从进化到志愿者。',
    originSummary_en: 'From Latin "volvere" (to roll, turn) and "voluntās" (will, wish).',
    originSummary_zh: '源自拉丁语 volvere（滚、转）和 voluntās（意志、愿望）。',
    related: ['vers', 'rot', 'circ'],
  },
  zo: {
    enMeaning: 'animal, living being',
    etymology: 'Greek zōion (ζῷον)',
    origin: 'Greek',
    domains: ['animals'],
    overview_en: 'A Greek root for animals, forming the vocabulary of zoology.',
    overview_zh: '希腊词根，表示动物，构成动物学的词汇。',
    originSummary_en: 'From Greek "zōion" (animal, living being).',
    originSummary_zh: '源自希腊语 zōion（动物、生物）。',
    related: ['bio', 'bot', 'viv'],
  },
};

// ── Get word lists from parsed data ──────────────────────────

const parsedRoots = new Map();
for (const r of PARSED.roots) {
  parsedRoots.set(r.slug, r);
}

// Merge ag into act
if (parsedRoots.has('ag') && parsedRoots.has('act')) {
  const act = parsedRoots.get('act');
  const ag = parsedRoots.get('ag');
  for (const v of ag.variants) {
    if (!act.variants.includes(v)) act.variants.push(v);
  }
  for (const w of ag.words) {
    if (!act.words.includes(w)) act.words.push(w);
  }
  parsedRoots.delete('ag');
}

// Merge bi into bio
if (parsedRoots.has('bi')) {
  const bio = parsedRoots.get('bio') || { slug: 'bio', variants: ['bio'], words: [] };
  const bi = parsedRoots.get('bi');
  for (const w of bi.words) {
    if (!bio.words.includes(w)) bio.words.push(w);
  }
  parsedRoots.delete('bi');
  if (!parsedRoots.has('bio')) parsedRoots.set('bio', bio);
}

// Rename sp -> spec, un -> uni, us -> util
const renames = { sp: 'spec', un: 'uni', us: 'util' };
for (const [from, to] of Object.entries(renames)) {
  if (parsedRoots.has(from)) {
    const r = parsedRoots.get(from);
    r.slug = to;
    parsedRoots.delete(from);
    parsedRoots.set(to, r);
  }
}

// ── Generate roots.ts ────────────────────────────────────────

const lines = [];
lines.push("import type { RootEntry } from '@/types/content';");
lines.push('');
lines.push('export const ROOTS: RootEntry[] = [');

// Sort all root slugs alphabetically
const allSlugs = [...parsedRoots.keys()].sort();

for (const slug of allSlugs) {
  const parsed = parsedRoots.get(slug);
  const enriched = ENRICHMENT[slug];

  if (!enriched) {
    console.warn(`WARNING: No enrichment data for root "${slug}", skipping`);
    continue;
  }

  const variants = parsed.variants.map((v) => `'${v}'`).join(', ');
  const words = parsed.words
    .slice(0, 20)
    .map((w) => `'${w}'`)
    .join(', ');
  const domains = enriched.domains.map((d) => `'${d}'`).join(', ');
  const related = enriched.related.map((r) => `'${r}'`).join(', ');

  lines.push('  {');
  lines.push(`    slug: '${slug}',`);
  lines.push(`    variants: [${variants}],`);
  lines.push(
    `    meaning: { en: '${enriched.enMeaning}', zh: '${parsed.meaningZh || enriched.enMeaning}' },`,
  );
  lines.push(`    languageOfOrigin: '${enriched.origin}',`);
  lines.push(`    etymology: '${enriched.etymology}',`);
  lines.push('    overview: {');
  lines.push(`      en: '${enriched.overview_en}',`);
  lines.push(`      zh: '${enriched.overview_zh}',`);
  lines.push('    },');
  lines.push('    originSummary: {');
  lines.push(`      en: '${enriched.originSummary_en}',`);
  lines.push(`      zh: '${enriched.originSummary_zh}',`);
  lines.push('    },');
  lines.push(`    semanticDomains: [${domains}],`);
  lines.push(`    relatedRoots: [${related}],`);
  lines.push(`    associatedWords: [${words}],`);
  if (enriched.grimm) {
    lines.push(`    grimmLawGroup: '${enriched.grimm}',`);
  }
  lines.push('  },');
}

lines.push('];');
lines.push('');
lines.push(
  'export const getRootBySlug = (slug: string) => ROOTS.find((root) => root.slug === slug);',
);
lines.push('');

writeFileSync(OUTPUT, lines.join('\n'), 'utf-8');
console.log(`Generated ${OUTPUT} with ${allSlugs.length} roots`);
